#!/usr/bin/env bash

db.privilege.update({_id: 40}, {$addToSet: {points: {id: 404, name: '控制', desc: ''}}})
db.privilege.update({_id: 70}, {$set: {points: [{"desc":"","name":"确认提示告警","id":702},{"desc":"","name":"强制结束提示告警","id":703},{"desc":"","name":"挂起提示告警","id":704},{"desc":"","name":"结束提示告警","id":705},{"desc":"","name":"确认一般告警","id":712},{"desc":"","name":"强制结束一般告警","id":713},{"desc":"","name":"挂起一般告警","id":714},{"desc":"","name":"结束一般告警","id":715},{"desc":"","name":"确认重要告警","id":722},{"desc":"","name":"强制结束重要告警","id":723},{"desc":"","name":"挂起重要告警","id":724},{"desc":"","name":"结束重要告警","id":725},{"desc":"","name":"确认紧急告警","id":732},{"desc":"","name":"强制结束紧急告警","id":733},{"desc":"","name":"挂起紧急告警","id":734},{"desc":"","name":"结束紧急告警","id":735}]}})
db.privilege.update({_id: 90}, {$set: {id:90,name:'联动',desc:'',points:[{id:901,name:'设置',desc:''},{id:902,name:'查询',desc:''}]}})
db.privilege.update({_id: 140}, {$set: {id: 140, name: "告警通知", points: [{"id":1401,"name":"设置","desc":""},{"id":1402,"name":"查询","desc":""}]}}, {upsert: true})

db.asset_type.update({system: 1}, {$set: {groups: [{"desc":"","name":"高压柜","group":1},{"desc":"","name":"中压柜","group":2},{"desc":"","name":"变压器","group":3},{"desc":"","name":"低压柜","group":4},{"desc":"","name":"柴油发电机","group":5},{"desc":"","name":"高压直流","group":6},{"desc":"","name":"UPS","group":7},{"desc":"","name":"-48V","group":8},{"desc":"","name":"蓄电池","group":9},{"desc":"","name":"列头柜","group":10},{"desc":"","name":"柴发配电柜","group":11},{"desc":"","name":"普通动力配电柜","group":12},{"desc":"","name":"PDU","group":13},{"desc":"","name":"直流屏","group":14},{"desc":"","name":"PLC控制柜","group":15}]}})
db.asset_type.update({system: 3}, {$set: {groups: [{"desc":"","name":"NVR","group":1},{"desc":"","name":"摄像头","group":2},{"desc":"","name":"门禁控制器","group":3},{"desc":"","name":"读卡器","group":4},{"desc":"","name":"动环采集器","group":5},{"desc":"","name":"电池巡检仪","group":6},{"desc":"","name":"漏水检测控制器","group":7},{"desc":"","name":"报警主机","group":8},{"desc":"","name":"红外探头","group":9},{"desc":"","name":"烟感","group":10},{"desc":"","name":"温感","group":11},{"desc":"","name":"消防主机","group":12},{"desc":"","name":"极早期","group":13},{"desc":"","name":"DDC控制器","group":14},{"desc":"","name":"BA网络控制器","group":15},{"desc":"","name":"BA监控系统","group":16},{"desc":"","name":"动环监控系统","group":17},{"desc":"","name":"CCTV视频监控系统","group":18},{"desc":"","name":"门禁监控系统","group":19}]}})
db.asset_type.update({system: 4}, {$set: {groups: [{"desc":"","name":"冷水机组","group":1},{"desc":"","name":"板换","group":2},{"desc":"","name":"冷却塔","group":3},{"desc":"","name":"水泵","group":4},{"desc":"","name":"蓄冷罐","group":5},{"desc":"","name":"精密空调","group":6},{"desc":"","name":"AHU","group":7},{"desc":"","name":"新风机","group":8},{"desc":"","name":"加湿机","group":9},{"desc":"","name":"阀门","group":10},{"desc":"","name":"环境传感器","group":11},{"desc":"","name":"水源热泵机组","group":12},{"desc":"","name":"水环热泵机组（液冷）","group":13},{"desc":"","name":"冷却塔（液冷）","group":14},{"desc":"","name":"水源机组供热泵","group":15},{"desc":"","name":"冷却水泵","group":16},{"desc":"","name":"水源机组冷却泵","group":17},{"desc":"","name":"冷却水泵（液冷）","group":18},{"desc":"","name":"冷冻水一次泵","group":19},{"desc":"","name":"冷冻水二次泵","group":20},{"desc":"","name":"冷却水加药装置","group":21},{"desc":"","name":"冷却水旁滤装置","group":22},{"desc":"","name":"冷却水旁滤装置（液冷）","group":23},{"desc":"","name":"冷冻水加药装置","group":24},{"desc":"","name":"水箱（液冷）","group":25},{"desc":"","name":"软化水箱","group":26},{"desc":"","name":"定压补水装置","group":27},{"desc":"","name":"新风机组（液冷）","group":28},{"desc":"","name":"直膨型精密空调机组（室内机）","group":29},{"desc":"","name":"直膨型精密空调机组（室外机）","group":30},{"desc":"","name":"风冷列间空调（室内机）","group":31},{"desc":"","name":"风冷列间空调（室外机）","group":32},{"desc":"","name":"冷冻水列间空调","group":33},{"desc":"","name":"风冷直膨热泵分体空调（柜式）","group":34},{"desc":"","name":"排风机","group":35},{"desc":"","name":"补风机","group":36},{"desc":"","name":"补热送风机","group":37},{"desc":"","name":"补热回风机","group":38},{"desc":"","name":"电真空热水锅炉","group":39},{"desc":"","name":"热水循环泵","group":40},{"desc":"","name":"贯流式电热风幕机","group":41},{"desc":"","name":"风机盘管","group":42},{"desc":"","name":"油烟净化机组","group":43},{"desc":"","name":"加湿器（液冷）","group":44}]}})
